### ISSUE TITLE
终于搭起了博客 | CalmCenter

### ISSUE THREAD

**Issue by CalmCenter** [CalmCenter/calmcenter.github.io#1]
https://calmcenter.github.io/2019/04/18/%E7%BB%88%E4%BA%8E%E6%90%AD%E8%B5%B7%E4%BA%86%E5%8D%9A%E5%AE%A2/ 

 一、为什么要写这篇文章各大网站关于搭建博客的文章已经不是一篇两篇了，但是他们的文章也有坑~(可能是版本问题)也各有各的特点，这里带你踩坑，并带你实现他们的特点，stormzhang 说过  把无序的信息变的有序，本质上也是信息差，也是可以创造价值的。  所以我准备整理一下各各博客的特点，尽力写成一本大全。 二、本文主要记载 搭建本地博客 部署到Github Pages 管理代码(git 基本操作)

**Comment by CalmCenter** [comment]
**不怕你搭博客，就怕你不坚持**

**Comment by SongYueXia** [comment]
support  calmcenter lv!(test)
