### ISSUE TITLE
categories | CalmCenter

### ISSUE THREAD

**Issue by CalmCenter** [CalmCenter/calmcenter.github.io#7]
https://calmcenter.github.io/links/

**Comment by JacobZjw** [comment]
交换友链吧~www.jbblogs.cn

**Comment by CalmCenter** [comment]
> @JacobZjw
> 交换友链吧~www.jbblogs.cn

```
  - nickname: CalmCenter  #友链名称
    avatar: https://raw.githubusercontent.com/CalmCenter/picGo/master/pictures/20190426182019.jpg  #友链头像
    site: https://calmcenter.club/  #友链地址
    info: 目标设置到月球，即使陨落也是在群星之间！  #友链说明
```
**评论区贴出就会上墙~**

**Comment by JacobZjw** [comment]
> @CalmCenter
> > @JacobZjw
> > 交换友链吧~www.jbblogs.cn
> 
> ```
>   - nickname: CalmCenter  #友链名称
>     avatar: https://raw.githubusercontent.com/CalmCenter/picGo/master/pictures/20190426182019.jpg  #友链头像
>     site: https://calmcenter.club/  #友链地址
>     info: 目标设置到月球，即使陨落也是在群星之间！  #友链说明
> ```
> **评论区贴出就会上墙~**

  - nickname: Jacob's blog  #友链名称
    avatar: https://s2.ax1x.com/2019/07/08/ZrWgC6.jpg  #友链头像
    site: https://www.jbblogs.cn/  #友链地址
    info: 生命不息，奋斗不止！  #友链说明

**Comment by CalmCenter** [comment]
> @JacobZjw

博主的血小板还可以添加点击跳舞的，待我更新我的 Live2d 文章，期间希望您配合测试可否？可以的话右下角 DaoVoice 私聊

**Comment by JacobZjw** [comment]
> @CalmCenter
> > @JacobZjw
> 
> 博主的血小板还可以添加点击跳舞的，待我更新我的 Live2d 文章，期间希望您配合测试可否？可以的话右下角 DaoVoice 私聊

好的
> @CalmCenter
> > @JacobZjw
> 
> 博主的血小板还可以添加点击跳舞的，待我更新我的 Live2d 文章，期间希望您配合测试可否？可以的话右下角 DaoVoice 私聊

好的
